apiVersion: apps/v1
kind: Deployment
metadata:
  name: crwd-app-deployment #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
  namespace: crwd
  labels:
    app: py-app
spec:
  replicas: 2 #The number of pods to be created in the Kubernetes cluster for the Py application container
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
      - name: py-app #The name of the py app application container
        image: catalincatana/crwd-repository:latest #The Docker image for building the py application container
        ports:
        - containerPort: 5000 #The port for the py application   container

---
apiVersion: v1
kind: Service
metadata:
  name: crwd-app-service #The name of the Kubernetes Service to be created in the Kubernetes cluster
  namespace: crwd
spec:
  selector:
    app: py-app
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 5000 #Service port
    targetPort: 5000 #The port for the Py application container